set path2par $env(MMGBSA_PARAM_DIR)
structure prot.psf
coordinates prot.pdb
paraTypeCharmm on
parameters $path2par/par_all36m_prot.prm
parameters $path2par/par_all36_na.prm
outputname mmgbsa_prot
numsteps 0
GBIS on
solventDielectric 78.5
ionConcentration 0.3
GBISBeta 0.8
alphaCutoff 15
sasa on
surfaceTension 0.00542
switching on
switchdist 15
cutoff 16
pairlistdist 18
timestep 2
nonbondedFreq 2
fullElectFrequency 4
exclude scaled1-4
temperature 298
set ts 0
coorfile open dcd sumtraj.prot.dcd
while {![coorfile read]} {
    firstTimestep $ts
    run 0
    incr ts
}
coorfile close
